### PR TITLE
Update cats effect, fs2, scala 3, etc

### PR DESCRIPTION
**Pull request by qwbarch**
I'm attempting to help update the dependencies for rediculous, but I'm a little stuck right now.  
Can you look over it when you have time and let me know if I'm on the right track?

### CODE REVIEW

**Comment by qwbarch** [comment]
https://github.com/davenverse/rediculous/blob/2fe4edabf0724c95ecbc7c6d8abe138a873b89d3/core/src/main/scala/io/chrisdavenport/rediculous/RedisConnection.scala#L234

The compiler complains about ``ClusterSlots`` not being found. I tried importing the following:
``import _root_.io.chrisdavenport.rediculous.cluster.ClusterSlots``
I can't understand what's wrong here, any ideas?

**Comment by qwbarch** [comment]
https://github.com/davenverse/rediculous/blob/2fe4edabf0724c95ecbc7c6d8abe138a873b89d3/core/src/main/scala/io/chrisdavenport/rediculous/RedisConnection.scala#L244

I forgot to uncomment while I was trying to isolate and fix other errors first.  
From looking at the fs2 source code in ``series/2.5.x``, ``Stream#chunks`` outputs all the chunks of the stream.  
``val chunk = chunkChunk.flatten`` is equivalent to emitting as a single chunk right?  
Would the correct replacement now be ``Stream#fromQueueUnterminatedChunk``?

**Comment by ChristopherDavenport** [comment]
I'm going to see if this will work with just ce3 and then attempt scala 3 after I think the two are making this edge case more complex.

**Comment by ChristopherDavenport** [comment]
Moved forward with #19 , should be useable safely from the JVM, the JS components are the experimenatl parts of fs2.

**Pull request closed without merging**
